# Pipeline Hierarchial Flow: Stages -> Stage -> Jobs -> Job -> Steps -> Task1, Task2, Task3  

trigger:
- main

stages:
  - stage: Build
    displayName: Build Stage
    jobs:
    - job: Build
      displayName: Build Job
      pool:
        vmImage: 'ubuntu-latest'
      steps:
      # Task-1: Build Docker Image and push to Azure Container Registry ACR
        

