# Pipeline Hierarchial Flow: Stages -> Stage -> Jobs -> Job -> Steps -> Task1, Task2, Task3  

trigger:
- main

stages:
  - stage: Build
    displayName: Build Stage
    jobs:
    - job: Build
      displayName: Build Job
      pool:
        vmImage: 'ubuntu-latest'
      steps:
      # Task-1: Build Docker Image and push to Azure Container Registry ACR
      - task: Docker@2
        displayName: ImageBuildAndPush
        inputs:
          containerRegistry: 'acr_container_service_connection'
          repository: $(repository_name)
          command: 'buildAndPush'
          Dockerfile: '**/nginx_nonroot_docker/Dockerfile'
          tags: v$(Build.BuildId)
      
      # Publish Artifacts pipeline code in addition to Build and Push          
      - bash: echo Contents in System Default Working Directory; ls -R $(System.DefaultWorkingDirectory)        
      - bash: echo Before copying Contents in Build Artifact Directory; ls -R $(Build.ArtifactStagingDirectory) 
      # Task-2: Copy files (Copy files from a source folder to target folder)
      # Source Directory: $(System.DefaultWorkingDirectory)/aks_deployment
      # Target Directory: $(Build.ArtifactStagingDirectory)
      - task: CopyFiles@2
        displayName: CopyManifestToWorkingDir
        inputs:
          SourceFolder: '$(System.DefaultWorkingDirectory)/aks_deployment'
          Contents: '**'
          TargetFolder: '$(Build.ArtifactStagingDirectory)'
          OverWrite: true
      # List files from Build Artifact Staging Directory - After Copy
      - bash: echo After copying to Build Artifact Directory; ls -R $(Build.ArtifactStagingDirectory)  
      # Task-3: Publish build artifacts (Publish build to Azure Pipelines) 
      - task: PublishBuildArtifacts@1
        inputs:
          PathtoPublish: '$(Build.ArtifactStagingDirectory)'
          ArtifactName: 'aks_deployment'
          publishLocation: 'Container'