trigger:
- main

#if u want to trigger the pipeline automatically when the main branch gets commited,
#unblock the below trigger block & block the above trigger block
#trigger:
#  branches:
#    include:
#      - main

pool:
  vmImage: ubuntu-latest

- task: CmdLine@2
  inputs:
    script: |
      echo Write your commands here
      
      echo Hello world
